### ISSUE TITLE
AGN accretion rate

### ISSUE THREAD

**Issue by JohannesBuchner** [darrencroton/sage#1]
Hi Darren,

I would like to implement a simple observationally-motivated model of AGN obscuration on top of SAGE, which hopefully would also make it into TAO. 
Could you point out to me where the AGN accretion rate is stored, I could not find it in do_AGN_heating?

Cheers,
               Johannes

**Comment by darrencroton** [comment]
Hi Johannes.

Have a look at line 151 of do_AGN_heating:

```
    if (AGNheating > 0.0)
        Gal[centralgal].Heating += 0.5 * AGNheating * Gal[centralgal].Vvir * Gal[centralgal].Vvir;
```

Does that help?

As an aside, i’m very keen to be involved in any such updates and to help where needed. If that sound of interest to you then feel free to keep in the loop. If not, no worries!

Good luck with it.
Darren

On 2 April 2016 at 1:26:02 AM, Johannes Buchner (notifications@github.com) wrote:

Hi Darren,

I would like to implement a simple observationally-motivated model of AGN obscuration on top of SAGE, which hopefully would also make it into TAO.
Could you point out to me where the AGN accretion rate is stored, I could not find it in do_AGN_heating?

Cheers,
Johannes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

## 

Darren Croton
Professor of Astrophysics
Centre for Astrophysics & Supercomputing
Swinburne University of Technology
PO Box 218, Hawthorn, VIC 3122, Australia
Phone: 61-3-9214-5537; Fax: 61-3-9214-8797
http://astronomy.swin.edu.au/~dcroton
